# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@types/node@26.5.1" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-26.5.1.tgz";
    hash = "sha512-CzNm2FezW4VR/LjG6yUdiEgLE/rAQ9Slj5gCu/C2VrdcW7I0ahNZ8DRbHT7zOZ6r3ONgd/bsQIeSaoDGrd1C6g==";
  };
  "remeda@2.33.7" = fetchurl {
    url = "https://registry.npmjs.org/remeda/-/remeda-2.33.7.tgz";
    hash = "sha512-cXlyjevWx5AcslOUEETG4o8XYi9UkoCXcJmj7XhPFVbla+ITuOBxv6ijBrmbeg+ZhzmDThkNdO+iXKUfrJep1w==";
  };
  "undici-types@8.9.0" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-8.9.0.tgz";
    hash = "sha512-KTDyRTYX8sWmKXAikPHHSyc63CRPETMctyjKFupcC6OBLXT3xsN0e9aF7m+mIXutFWpUXuedtowG7iLOzp0kQg==";
  };
  "zod@3.24.2" = fetchurl {
    url = "https://registry.npmjs.org/zod/-/zod-3.24.2.tgz";
    hash = "sha512-lY7CDW43ECgW9u1TcT3IoXHflywfVqDYze4waEz812jR/bZ8FHDsl7pFQoSZTz5N+2NqRXs8GBwnAwo3ZNxqhQ==";
  };
}