# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "acorn@8.18.0" = fetchurl {
    url = "https://registry.npmjs.org/acorn/-/acorn-8.18.0.tgz";
    hash = "sha512-lGq+9yr1/GuAWaVYIHRjvvySG5/4VfKIvC8EWxStPdcDh/Ka7FG3twP6v4d5BkravUilhIAsG4Qj83t02LWUPQ==";
  };
  "ansis@4.4.0" = fetchurl {
    url = "https://registry.npmjs.org/ansis/-/ansis-4.4.0.tgz";
    hash = "sha512-9k3v7xcHwgdO/DruxGIg4HtjvlAZlcnsX/mzqUb1t3NkYnl9kK2UJ+Gq0io+vQf7iT//BD/HB/NBkUR1LWxoeA==";
  };
  "anymatch@3.1.3" = fetchurl {
    url = "https://registry.npmjs.org/anymatch/-/anymatch-3.1.3.tgz";
    hash = "sha512-KMReFUr0B4t+D+OBkjR3KYqvocp2XaSzO55UcB6mgQMd3KbcE+mWTyvVV7D/zsdEbNnV6acZUutkiHQXvTr1Rw==";
  };
  "binary-extensions@2.3.0" = fetchurl {
    url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-2.3.0.tgz";
    hash = "sha512-Ceh+7ox5qe7LJuLHoY0feh3pHuUDHAcRUeyL2VYghZwfpkNIy/+8Ocg0a3UuSoYzavmylwuLWQOf3hl0jjMMIw==";
  };
  "braces@3.0.3" = fetchurl {
    url = "https://registry.npmjs.org/braces/-/braces-3.0.3.tgz";
    hash = "sha512-yQbXgO/OSZVD2IsiLlro+7Hf6Q18EJrKSEsdoMzKePKXct3gvD8oLcOQdIzGupr5Fj+EDe8gO/lxc1BzfMpxvA==";
  };
  "bundle-name@4.1.1" = fetchurl {
    url = "https://registry.npmjs.org/bundle-name/-/bundle-name-4.1.1.tgz";
    hash = "sha512-DdH81/zPLVS11EUgWq3tEu/xn+EzljlMYooDNdzWEnFha3R3NBMpMV1UqYIpjYHV/SgpFKMIX1Oh7o06SjM/oA==";
  };
  "c12@1.11.2" = fetchurl {
    url = "https://registry.npmjs.org/c12/-/c12-1.11.2.tgz";
    hash = "sha512-oBs8a4uvSDO9dm8b7OCFW7+dgtVrwmwnrVXYzLm43ta7ep2jCn/0MhoUFygIWtxhyy6+/MG7/agvpY0U1Iemew==";
  };
  "c12@3.3.4" = fetchurl {
    url = "https://registry.npmjs.org/c12/-/c12-3.3.4.tgz";
    hash = "sha512-cM0ApFQSBXuourJejzwv/AuPRvAxordTyParRVcHjjtXirtkzM0uK2L9TTn9s0cXZbG7E55jCivRQzoxYmRAlA==";
  };
  "cac@7.0.0" = fetchurl {
    url = "https://registry.npmjs.org/cac/-/cac-7.0.0.tgz";
    hash = "sha512-tixWYgm5ZoOD+3g6UTea91eow5z6AAHaho3g0V9CNSNb45gM8SmflpAc+GRd1InC4AqN/07Unrgp56Y94N9hJQ==";
  };
  "changelogen@0.5.7" = fetchurl {
    url = "https://registry.npmjs.org/changelogen/-/changelogen-0.5.7.tgz";
    hash = "sha512-cTZXBcJMl3pudE40WENOakXkcVtrbBpbkmSkM20NdRiUqa4+VYRdXdEsgQ0BNQ6JBE2YymTNWtPKVF7UCTN5+g==";
  };
  "changelogithub@15.0.5" = fetchurl {
    url = "https://registry.npmjs.org/changelogithub/-/changelogithub-15.0.5.tgz";
    hash = "sha512-GjRsZ+TPHieTBu8pMGP8pv2CdpCPl+OVDbz+oTxFwNIihCvg69oqsx+epo7EXypzSF46gr3HJPOTTjxm1nQRgw==";
  };
  "chokidar@3.6.0" = fetchurl {
    url = "https://registry.npmjs.org/chokidar/-/chokidar-3.6.0.tgz";
    hash = "sha512-7VT13fmjotKpGipCW9JEQAusEPE+Ei8nl6/g4FBAmIm0GOOLMua9NDDo/DWp0ZAxCr3cPq5ZpBqmPAQgDda2Pw==";
  };
  "chokidar@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/chokidar/-/chokidar-5.0.0.tgz";
    hash = "sha512-TQMmc3w+5AxjpL8iIiwebF73dRDF4fBIieAqGn9RGCWaEVwQ6Fb2cGe31Yns0RRIzii5goJ1Y7xbMwo1TxMplw==";
  };
  "chownr@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/chownr/-/chownr-2.0.0.tgz";
    hash = "sha512-bIomtDF5KGpdogkLd9VspvFzk9KfpyyGlS8YFVZl7TGPBHL5snIOnxeshwVgPteQ9b4Eydl+pVbIyE1DcvCWgQ==";
  };
  "citty@0.1.6" = fetchurl {
    url = "https://registry.npmjs.org/citty/-/citty-0.1.6.tgz";
    hash = "sha512-tskPPKEs8D2KPafUypv2gxwJP8h/OaJmC82QQGGDQcHvXX43xF2VDACcJVmZ0EuSxkpO9Kc4MlrA3q0+FG58AQ==";
  };
  "colorette@2.0.20" = fetchurl {
    url = "https://registry.npmjs.org/colorette/-/colorette-2.0.20.tgz";
    hash = "sha512-IfEDxwoWIjkeXL1eXcDiow4UbKjhLdq6/EuSVR9GMN7KVH3r9gQ83e73hsz1Nd1T3ijd5xv1wcWRYO+D6kCI2w==";
  };
  "confbox@0.1.8" = fetchurl {
    url = "https://registry.npmjs.org/confbox/-/confbox-0.1.8.tgz";
    hash = "sha512-RMtmw0iFkeR4YV+fUOSucriAQNb9g8zFR52MWCtl+cCZOFRNL6zeB395vPzFhEjjn4fMxXudmELnl/KF/WrK6w==";
  };
  "confbox@0.2.4" = fetchurl {
    url = "https://registry.npmjs.org/confbox/-/confbox-0.2.4.tgz";
    hash = "sha512-ysOGlgTFbN2/Y6Cg3Iye8YKulHw+R2fNXHrgSmXISQdMnomY6eNDprVdW9R5xBguEqI954+S6709UyiO7B+6OQ==";
  };
  "confbox@0.3.1" = fetchurl {
    url = "https://registry.npmjs.org/confbox/-/confbox-0.3.1.tgz";
    hash = "sha512-cKUSoKa8YxFZZSmraVi7onONx3amu77ngK3kGpsYHDH7drPwCRkQE1RYMPlLRrMtnciRj274XNRxcHxnKmDSnA==";
  };
  "consola@3.4.2" = fetchurl {
    url = "https://registry.npmjs.org/consola/-/consola-3.4.2.tgz";
    hash = "sha512-5IKcdX0nnYavi6G7TtOhwkYzyjfJlatbjMjuLSfE2kYT5pMDOilZ4OvMhi637CcDICTmz3wARPoyhqyX1Y+XvA==";
  };
  "convert-gitmoji@0.1.5" = fetchurl {
    url = "https://registry.npmjs.org/convert-gitmoji/-/convert-gitmoji-0.1.5.tgz";
    hash = "sha512-4wqOafJdk2tqZC++cjcbGcaJ13BZ3kwldf06PTiAQRAB76Z1KJwZNL1SaRZMi2w1FM9RYTgZ6QErS8NUl/GBmQ==";
  };
  "default-browser-id@5.0.1" = fetchurl {
    url = "https://registry.npmjs.org/default-browser-id/-/default-browser-id-5.0.1.tgz";
    hash = "sha512-x1VCxdX4t+8wVfd1so/9w+vQ4vx7lKd2Qp5tDRutErwmR85OgmfX7RlLRMWafRMY7hbEiXIbudNrjOAPa/hL8Q==";
  };
  "default-browser@5.5.1" = fetchurl {
    url = "https://registry.npmjs.org/default-browser/-/default-browser-5.5.1.tgz";
    hash = "sha512-m1pAzaJgZ/gssEqlOhJkPJp8Xly7QyW6xcrkUa2KKcDeDSEMP7X8xipU3snUcfisTQx0w1AGae+9UtJSfVnXGw==";
  };
  "define-lazy-prop@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/define-lazy-prop/-/define-lazy-prop-3.0.0.tgz";
    hash = "sha512-N+MeXYoqr3pOgn8xfyRPREN7gHakLYjhsHhWGT3fWAiL4IkAt0iDw14QiiEm2bE30c5XX5q0FtAA3CK5f9/BUg==";
  };
  "defu@6.1.7" = fetchurl {
    url = "https://registry.npmjs.org/defu/-/defu-6.1.7.tgz";
    hash = "sha512-7z22QmUWiQ/2d0KkdYmANbRUVABpZ9SNYyH5vx6PZ+nE5bcC0l7uFvEfHlyld/HcGBFTL536ClDt3DEcSlEJAQ==";
  };
  "destr@2.0.5" = fetchurl {
    url = "https://registry.npmjs.org/destr/-/destr-2.0.5.tgz";
    hash = "sha512-ugFTXCtDZunbzasqBxrK93Ik/DRYsO6S/fedkWEMKqt04xZ4csmnmwGDBAb07QWNaGMAmnTIemsYZCksjATwsA==";
  };
  "dotenv@16.6.1" = fetchurl {
    url = "https://registry.npmjs.org/dotenv/-/dotenv-16.6.1.tgz";
    hash = "sha512-uBq4egWHTcTt33a72vpSG0z3HnPuIl6NqYcTrKEg2azoEyl2hpW0zqlxysq2pK9HlDIHyHyakeYaYnSAwd8bow==";
  };
  "dotenv@17.4.2" = fetchurl {
    url = "https://registry.npmjs.org/dotenv/-/dotenv-17.4.2.tgz";
    hash = "sha512-nI4U3TottKAcAD9LLud4Cb7b2QztQMUEfHbvhTH09bqXTxnSie8WnjPALV/WMCrJZ6UV/qHJ6L03OqO3LcdYZw==";
  };
  "exsolve@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/exsolve/-/exsolve-1.1.1.tgz";
    hash = "sha512-9U/jZUgjnSGyntRr6y5Muu1MJcwFl6kPu7k8qLF0IMNfLqvw0NZ4nnVDq0RVoZ0RvCyumib4Ez3KYrVfilrw+g==";
  };
  "fdir@6.5.0" = fetchurl {
    url = "https://registry.npmjs.org/fdir/-/fdir-6.5.0.tgz";
    hash = "sha512-tIbYtZbucOs0BRGqPJkshJUYdL+SDH7dVM8gjy+ERp3WAUjLEFJE+02kanyHtwjWOnwrKYBiwAmM0p4kLJAnXg==";
  };
  "fill-range@7.1.1" = fetchurl {
    url = "https://registry.npmjs.org/fill-range/-/fill-range-7.1.1.tgz";
    hash = "sha512-YsGpe3WHLK8ZYi4tWDg2Jy3ebRz2rXowDxnld4bkQB00cc/1Zw9AWnC0i9ztDJitivtQvaI9KaLyKrc+hBW0yg==";
  };
  "fs-minipass@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/fs-minipass/-/fs-minipass-2.1.0.tgz";
    hash = "sha512-V/JgOLFCS+R6Vcq0slCuaeWEdNC3ouDlJMNIsacH2VtALiu9mV4LPrHc5cDl8k5aw6J8jwgWWpiTo5RYhmIzvg==";
  };
  "fsevents@2.3.3" = fetchurl {
    url = "https://registry.npmjs.org/fsevents/-/fsevents-2.3.3.tgz";
    hash = "sha512-5xoDfX+fL7faATnagmWPpbFtwh/R77WmMMqqHGS65C3vvB0YHrgF+B1YmZ3441tMj5n63k0212XNoJwzlhffQw==";
  };
  "giget@1.2.5" = fetchurl {
    url = "https://registry.npmjs.org/giget/-/giget-1.2.5.tgz";
    hash = "sha512-r1ekGw/Bgpi3HLV3h1MRBIlSAdHoIMklpaQ3OQLFcRw9PwAj2rqigvIbg+dBUI51OxVI2jsEtDywDBjSiuf7Ug==";
  };
  "giget@3.3.1" = fetchurl {
    url = "https://registry.npmjs.org/giget/-/giget-3.3.1.tgz";
    hash = "sha512-r+mvuDjrjMpsdw46Kmeydb8bdHm7wOKw8wNBtTndkjbPjgAp5oUJUxRE76wZFknxIPokfWvep2qSXK37aXE6zg==";
  };
  "glob-parent@5.1.2" = fetchurl {
    url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
    hash = "sha512-AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
  };
  "is-binary-path@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-2.1.0.tgz";
    hash = "sha512-ZMERYes6pDydyuGidse7OsHxtbI7WVeUEozgR/g7rd0xUimYNlvZRE/K2MgZTjWy725IfelLeVcEM97mmtRGXw==";
  };
  "is-docker@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-docker/-/is-docker-3.0.0.tgz";
    hash = "sha512-eljcgEDlEns/7AXFosB5K/2nCM4P7FQPkGc/DWLy5rmFEWvZayGrik1d9/QIY5nJ4f9YsVvBkA6kJpHn9rISdQ==";
  };
  "is-extglob@2.1.1" = fetchurl {
    url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
    hash = "sha512-SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
  };
  "is-glob@4.0.3" = fetchurl {
    url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
    hash = "sha512-xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
  };
  "is-inside-container@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-inside-container/-/is-inside-container-1.0.0.tgz";
    hash = "sha512-KIYLCCJghfHZxqjYBE7rEy0OBuTd5xCHS7tHVgvCLkx7StIoaxwNW3hCALgEUjFfeRk+MG/Qxmp/vtETEF3tRA==";
  };
  "is-number@7.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
    hash = "sha512-41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
  };
  "is-wsl@3.1.1" = fetchurl {
    url = "https://registry.npmjs.org/is-wsl/-/is-wsl-3.1.1.tgz";
    hash = "sha512-e6rvdUCiQCAuumZslxRJWR/Doq4VpPR82kqclvcS0efgt430SlGIk05vdCN58+VrzgtIcfNODjozVielycD4Sw==";
  };
  "jiti@1.21.7" = fetchurl {
    url = "https://registry.npmjs.org/jiti/-/jiti-1.21.7.tgz";
    hash = "sha512-/imKNG4EbWNrVjoNC/1H5/9GFy+tqjGBHCaSsN+P2RnPqjsLmv6UD3Ej+Kj8nBWaRAwyk7kK5ZUc+OEatnTR3A==";
  };
  "jiti@2.7.0" = fetchurl {
    url = "https://registry.npmjs.org/jiti/-/jiti-2.7.0.tgz";
    hash = "sha512-AC/7JofJvZGrrneWNaEnJeOLUx+JlGt7tNa0wZiRPT4MY1wmfKjt2+6O2p2uz2+skll8OZZmJMNqeke7kKbNgQ==";
  };
  "minipass@3.3.6" = fetchurl {
    url = "https://registry.npmjs.org/minipass/-/minipass-3.3.6.tgz";
    hash = "sha512-DxiNidxSEK+tHG6zOIklvNOwm3hvCrbUrdtzY74U6HKTJxvIDfOUL5W5P2Ghd3DTkhhKPYGqeNUIh5qcM4YBfw==";
  };
  "minipass@5.0.0" = fetchurl {
    url = "https://registry.npmjs.org/minipass/-/minipass-5.0.0.tgz";
    hash = "sha512-3FnjYuehv9k6ovOEbyOswadCDPX1piCfhV8ncmYtHOjuPwylVWsghTLo7rabjC3Rx5xD4HDx8Wm1xnMF7S5qFQ==";
  };
  "minizlib@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/minizlib/-/minizlib-2.1.2.tgz";
    hash = "sha512-bAxsR8BVfj60DWXHE3u30oHzfl4G7khkSuPW+qvpd7jFRHm7dLxOjUk1EHACJ/hxLY8phGJ0YhYHZo7jil7Qdg==";
  };
  "mkdirp@1.0.4" = fetchurl {
    url = "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz";
    hash = "sha512-vVqVZQyf3WLx2Shd0qJ9xuvqgAyKPLAiqITEtqW0oIUjzo3PePDd6fW9iFz30ef7Ysp/oiWqbhszeGWW2T6Gzw==";
  };
  "mlly@1.8.2" = fetchurl {
    url = "https://registry.npmjs.org/mlly/-/mlly-1.8.2.tgz";
    hash = "sha512-d+ObxMQFmbt10sretNDytwt85VrbkhhUA/JBGm1MPaWJ65Cl4wOgLaB1NYvJSZ0Ef03MMEU/0xpPMXUIQ29UfA==";
  };
  "mri@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/mri/-/mri-1.2.0.tgz";
    hash = "sha512-tzzskb3bG8LvYGFF/mDTpq3jpI6Q9wc3LEmBaghu+DdCssd1FakN7Bc0hVNmEyGq1bq3RgfkCb3cmQLpNPOroA==";
  };
  "node-fetch-native@1.6.7" = fetchurl {
    url = "https://registry.npmjs.org/node-fetch-native/-/node-fetch-native-1.6.7.tgz";
    hash = "sha512-g9yhqoedzIUm0nTnTqAQvueMPVOuIY16bqgAJJC8XOOubYFNwz6IER9qs0Gq2Xd0+CecCKFjtdDTMA4u4xG06Q==";
  };
  "normalize-path@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/normalize-path/-/normalize-path-3.0.0.tgz";
    hash = "sha512-6eZs5Ls3WtCisHWp9S2GUy8dqkpGi4BVSz3GaqiE6ezub0512ESztXUwUB6C6IKbQkY2Pnb/mD4WYojCRwcwLA==";
  };
  "nypm@0.5.4" = fetchurl {
    url = "https://registry.npmjs.org/nypm/-/nypm-0.5.4.tgz";
    hash = "sha512-X0SNNrZiGU8/e/zAB7sCTtdxWTMSIO73q+xuKgglm2Yvzwlo8UoC5FNySQFCvl84uPaeADkqHUZUkWy4aH4xOA==";
  };
  "ofetch@1.5.1" = fetchurl {
    url = "https://registry.npmjs.org/ofetch/-/ofetch-1.5.1.tgz";
    hash = "sha512-2W4oUZlVaqAPAil6FUg/difl6YhqhUR7x2eZY4bQCko22UXg3hptq9KLQdqFClV+Wu85UX7hNtdGTngi/1BxcA==";
  };
  "ohash@1.1.6" = fetchurl {
    url = "https://registry.npmjs.org/ohash/-/ohash-1.1.6.tgz";
    hash = "sha512-TBu7PtV8YkAZn0tSxobKY2n2aAQva936lhRrj6957aDaCf9IEtqsKbgMzXE/F/sjqYOwmrukeORHNLe5glk7Cg==";
  };
  "ohash@2.0.12" = fetchurl {
    url = "https://registry.npmjs.org/ohash/-/ohash-2.0.12.tgz";
    hash = "sha512-65S/5gk9YSsaRjcyf7Nfa6h/d3E8/1gslpXfI4W7Dxn/oap8IKRuNT5VXkLQ1YFKIEg4apRY4Pj6aiwFzrDdmw==";
  };
  "open@10.2.0" = fetchurl {
    url = "https://registry.npmjs.org/open/-/open-10.2.0.tgz";
    hash = "sha512-YgBpdJHPyQ2UE5x+hlSXcnejzAvD0b22U2OuAP+8OnlJT+PjWPxtgmGqKKc+RgTM63U9gN0YzrYc71R2WT/hTA==";
  };
  "pathe@1.1.2" = fetchurl {
    url = "https://registry.npmjs.org/pathe/-/pathe-1.1.2.tgz";
    hash = "sha512-whLdWMYL2TwI08hn8/ZqAbrVemu0LNaNNJZX73O6qaIdCTfXutsLhMkjdENX0qhsQ9uIimo4/aQOmXkoon2nDQ==";
  };
  "pathe@2.0.3" = fetchurl {
    url = "https://registry.npmjs.org/pathe/-/pathe-2.0.3.tgz";
    hash = "sha512-WUjGcAqP1gQacoQe+OBJsFA7Ld4DyXuUIjZ5cc75cLHvJ7dtNsTugphxIADwspS+AraAUePCKrSVtPLFj/F88w==";
  };
  "perfect-debounce@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/perfect-debounce/-/perfect-debounce-1.0.0.tgz";
    hash = "sha512-xCy9V055GLEqoFaHoC1SoLIaLmWctgCUaBaWxDZ7/Zx4CTyX7cJQLJOok/orfjZAh9kEYpjJa4d0KcJmCbctZA==";
  };
  "perfect-debounce@2.1.0" = fetchurl {
    url = "https://registry.npmjs.org/perfect-debounce/-/perfect-debounce-2.1.0.tgz";
    hash = "sha512-LjgdTytVFXeUgtHZr9WYViYSM/g8MkcTPYDlPa3cDqMirHjKiSZPYd6DoL7pK8AJQr+uWkQvCjHNdiMqsrJs+g==";
  };
  "picomatch@2.3.2" = fetchurl {
    url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.2.tgz";
    hash = "sha512-V7+vQEJ06Z+c5tSye8S+nHUfI51xoXIXjHQ99cQtKUkQqqO1kO/KCJUfZXuB47h/YBlDhah2H3hdUGXn8ie0oA==";
  };
  "picomatch@4.0.7" = fetchurl {
    url = "https://registry.npmjs.org/picomatch/-/picomatch-4.0.7.tgz";
    hash = "sha512-qcJu88Q2IWqJsDD529JKMdwGm/dvInW4HvQnRwiH9JtihJvzGOscDtHE3x1pBKeUOTysQ8kVmLnJ2kJu7yhcGA==";
  };
  "pkg-types@1.3.1" = fetchurl {
    url = "https://registry.npmjs.org/pkg-types/-/pkg-types-1.3.1.tgz";
    hash = "sha512-/Jm5M4RvtBFVkKWRu2BLUTNP8/M2a+UwuAX+ae4770q1qVGtfjG+WTCupoZixokjmHiry8uI+dlY8KXYV5HVVQ==";
  };
  "pkg-types@2.3.3" = fetchurl {
    url = "https://registry.npmjs.org/pkg-types/-/pkg-types-2.3.3.tgz";
    hash = "sha512-j/lCFdcppV0JxWpCEITdbDltBxPP6cHT+yNJ6Go2OgoSA9518X847X9z0p6LtA4Nc16+eQzCZjRrWanTGvHJ5w==";
  };
  "rc9@2.1.2" = fetchurl {
    url = "https://registry.npmjs.org/rc9/-/rc9-2.1.2.tgz";
    hash = "sha512-btXCnMmRIBINM2LDZoEmOogIZU7Qe7zn4BpomSKZ/ykbLObuBdvG+mFq11DL6fjH1DRwHhrlgtYWG96bJiC7Cg==";
  };
  "rc9@3.1.0" = fetchurl {
    url = "https://registry.npmjs.org/rc9/-/rc9-3.1.0.tgz";
    hash = "sha512-ufjkNVzbRHKcCOmTahZkmVsyc3W+MSk3jY03m+a7tGHkIsdVMG9l10/3HvFbWkkKzY5VFp3pkRsIo/UYgmFL7Q==";
  };
  "readdirp@3.6.0" = fetchurl {
    url = "https://registry.npmjs.org/readdirp/-/readdirp-3.6.0.tgz";
    hash = "sha512-hOS089on8RduqdbhvQ5Z37A0ESjsqz6qnRcffsMU3495FuTdqSm+7bhJ29JvIOsBDEEnan5DPu9t3To9VRlMzA==";
  };
  "readdirp@5.1.1" = fetchurl {
    url = "https://registry.npmjs.org/readdirp/-/readdirp-5.1.1.tgz";
    hash = "sha512-Kko+Y5XQ6fM+Ce3dq3m9YGxnacYZYl9cA1wZjaF3Vbry2L3i1qVg8+CAgNPsXRArPMUMCaOR7oa9Nqntc43JKA==";
  };
  "run-applescript@7.1.0" = fetchurl {
    url = "https://registry.npmjs.org/run-applescript/-/run-applescript-7.1.0.tgz";
    hash = "sha512-DPe5pVFaAsinSaV6QjQ6gdiedWDcRCbUuiQfQa2wmWV7+xC9bGulGI8+TdRmoFkAPaBXk8CrAbnlY2ISniJ47Q==";
  };
  "scule@1.3.0" = fetchurl {
    url = "https://registry.npmjs.org/scule/-/scule-1.3.0.tgz";
    hash = "sha512-6FtHJEvt+pVMIB9IBY+IcCJ6Z5f1iQnytgyfKMhDKgmzYG+TeH/wx1y3l27rshSbLiSanrR9ffZDrEsmjlQF2g==";
  };
  "semver@7.8.5" = fetchurl {
    url = "https://registry.npmjs.org/semver/-/semver-7.8.5.tgz";
    hash = "sha512-Y7/KDsb8LjooZpwaqGyulO6DQlksgCncchHGk+sZIY4SBvUocMBEFH5Ur1fI4dV+Jvl0w6cjvucaIi40puRioA==";
  };
  "std-env@3.10.0" = fetchurl {
    url = "https://registry.npmjs.org/std-env/-/std-env-3.10.0.tgz";
    hash = "sha512-5GS12FdOZNliM5mAOxFRg7Ir0pWz8MdpYm6AY6VPkGpbA7ZzmbzNcBJQ0GPvvyWgcY7QAhCgf9Uy89I03faLkg==";
  };
  "tar@6.2.1" = fetchurl {
    url = "https://registry.npmjs.org/tar/-/tar-6.2.1.tgz";
    hash = "sha512-DZ4yORTwrbTj/7MZYq2w+/ZFdI6OZ/f9SFHR+71gIVUZhOQPHzVCLpvRnPgyaMpfWxxk/4ONva3GQSyNIKRv6A==";
  };
  "tinyexec@0.3.2" = fetchurl {
    url = "https://registry.npmjs.org/tinyexec/-/tinyexec-0.3.2.tgz";
    hash = "sha512-KQQR9yN7R5+OSwaK0XQoj22pwHoTlgYqmUscPYoknOoWCWfj/5/ABTMRi69FrKU5ffPVh5QcFikpWJI/P1ocHA==";
  };
  "tinyexec@1.3.1" = fetchurl {
    url = "https://registry.npmjs.org/tinyexec/-/tinyexec-1.3.1.tgz";
    hash = "sha512-GCvB3aoys96IuDFBMcTB46JOR6mdMtAToqwiW8JlWhsoh1mhHi/xn9ss/Dg7N555GiJyEt2qzoG/NHCwM6h1EA==";
  };
  "tinyglobby@0.2.17" = fetchurl {
    url = "https://registry.npmjs.org/tinyglobby/-/tinyglobby-0.2.17.tgz";
    hash = "sha512-wXR/dYpcqKmfWpEdZjiKJOwCNFndD0DMnrW/cYjVGttEkBfVgcLFHoNrlj47mjOVic9yyNu65alsgF4NQyTa2g==";
  };
  "to-regex-range@5.0.1" = fetchurl {
    url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
    hash = "sha512-65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
  };
  "ufo@1.6.4" = fetchurl {
    url = "https://registry.npmjs.org/ufo/-/ufo-1.6.4.tgz";
    hash = "sha512-JFNbkD1Svwe0KvGi8GOeLcP4kAWQ609twvCdcHxq1oSL8svv39ZuSvajcD8B+5D0eL4+s1Is2D/O6KN3qcTeRA==";
  };
  "verkit@0.4.1" = fetchurl {
    url = "https://registry.npmjs.org/verkit/-/verkit-0.4.1.tgz";
    hash = "sha512-mMVzj0TXExtVdlDEq+Mzp0eyOuyznNpFobNM3uAqe3HVm/Ps2c+u17BligMkZjZCA6EiXpoon8iRTer3iu40SQ==";
  };
  "wsl-utils@0.1.0" = fetchurl {
    url = "https://registry.npmjs.org/wsl-utils/-/wsl-utils-0.1.0.tgz";
    hash = "sha512-h3Fbisa2nKGPxCpm89Hk33lBLsnaGBvctQopaBSOW/uIs6FTe1ATyAnKFJrzVs9vpGdsTe73WF3V4lIsk4Gacw==";
  };
  "yallist@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
    hash = "sha512-3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
  };
  "yaml@2.9.1" = fetchurl {
    url = "https://registry.npmjs.org/yaml/-/yaml-2.9.1.tgz";
    hash = "sha512-3NxN8+78OdzbT7C/WjGsyfPAtJaN3FNDsWxv7Y7mcDsT/oOmgW8BpyQQFFBnvZE3j9Y2Sdz1ULFLezL7Eb2yFw==";
  };
}